### ISSUE TITLE
Please catch up LINE Login v2.1

### ISSUE THREAD

**Issue by kazuki-ma** [nitzo/passport-line#2]
Recently LINE releases LINE Login v2.1.

LINE Login v2.1 has following changes.

* [ ] ID tokens https://developers.line.me/en/docs/line-login/web/integrate-line-login/#id-tokens
* [x] Authentication and authorization process. https://developers.line.me/en/docs/line-login/web/integrate-line-login/#authentication-and-authorization-process
* [x] Updated endpoints 

Memo: passport-line's strategy handles profile request and users don't feel merit of ID tokens. So Authentication and authorization process enhancement is first priority. Updating endpoints is needed for process enhancement.

Memo: Java's example (not SDK) has same issue https://github.com/line/line-login-sample-for-spring-security/issues/3.

**Comment by nitzo** [comment]
Hi @kazuki-ma 
Thanks a lot for the pull requests. I have merged them.

Regarding to ID tokens since passport handles the user's profile request I don't think there is a need to use the openid scope. Please correct me if I am wrong. 

Closing this issue.

**Comment by kazuki-ma** [comment]
@nitzo 
Year. I have same opinion with you. Thank you reviewing the PR. 😄
