### ISSUE TITLE
profile.pictureUrl returns undefined

### ISSUE THREAD

**Issue by develanet** [nitzo/passport-line#6]
When I `console.log(profile)` in my **new LineStrategy**, I see the pictureUrl in the console, but can't seem to save the **profile.pictureUrl** string to the DB as it is undefined. 

**Working solution:** 

**add: `profile.pictureUrl = json.pictureUrl;`** 
directly beneath: `profile.displayName = json.displayName;`
in:  `/passport-line/lib/strategy.js`

**Comment by nitzo** [comment]
Hi @omgitsisaias !

Thanks for you note.
I will add this fix now.
Please note that you can always access the "raw" profile data received from LINE by using profile._json

Thanks!

**Comment by nitzo** [comment]
Fixed and published.
